# https://gohugo.io/overview/configuration/

baseurl = "/"
languageCode = "en-us"
title = "Sisu Hugo Static Site Starter"

# Directory locations
publishDir = "dist"
archetypeDir = "src/markup/archetypes"
contentDir = "src/markup/content"
dataDir = "src/markup/data"
layoutDir = "src/markup/layouts"
themesDir = "src/markup/themes"

# Use TOML for front matter
metaDataFormat = "toml"

# Outputs
# Save home page as JSON and use that to create an searchable index of the site
[outputs]
  home = [ "HTML", "JSON"]
  page = [ "HTML"]

# Taxonomies
# Leave empty to remove Category and Tags
[taxonomies]
